# Generated by Django 4.2.4 on 2023-08-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eightStore', '0006_toy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='image',
            field=models.ImageField(null=True, upload_to='static/toys'),
        ),
    ]
