# Generated by Django 4.2.4 on 2023-08-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eightStore', '0007_alter_toy_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
        migrations.AddField(
            model_name='customer',
            name='fname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='lname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='passwd',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
