# Generated by Django 4.2.4 on 2023-08-28 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eightStore', '0010_remove_game_category_game_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eightStore.category'),
        ),
    ]
