# Generated by Django 4.2.4 on 2023-08-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eightStore', '0012_toycategory_alter_toy_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toy',
            old_name='name',
            new_name='title',
        ),
    ]
