# Generated by Django 4.2.4 on 2023-08-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eightStore', '0013_rename_name_toy_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AddField(
            model_name='order',
            name='cityPostCode',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='customerAdress',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customerCity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customerCountry',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
