# Generated by Django 4.2.4 on 2023-08-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eightStore', '0014_remove_order_order_date_order_citypostcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='toy',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
